import { LightningElement , track} from 'lwc';
import getAccountList from "@salesforce/apex/AccountController.getAccList";

export default class DragRecords extends LightningElement {
	@track jsonItem=[{
		"topicLink": "/s/topic/0TO0y000000cKUEGA2/Getting Started",
		"Id": "0TO0y000000cKUEGA2",
		"order": null,
		"name": "Getting Started",
		"label": "Getting Started",
		"items": [{
			"topicLink": null,
			"recordId": "ka08b000000VU5xAAG",
			"order": 1,
			"name": "overview",
			"label": "Get Started with  Advertising",
			"items": [],
			"isKnowledge": true,
			"identityKeyName": null,
			"identityKeyDesc": null,
			"expanded": false,
			"description": "Learn how to begin advertising on .",
			"articleType": "Forbusiness External"
		},
		{
			"topicLink": null,
			"recordId": "ka08b000000VU6kAAG",
			"order": 2,
			"name": "value-of-",
			"label": "The Value of Advertising on ",
			"items": [],
			"isKnowledge": true,
			"identityKeyName": null,
			"identityKeyDesc": null,
			"expanded": false,
			"description": "Learn more about how advertising on  can help bring value to your business.",
			"articleType": "Forbusiness External"
		},
		{
			"topicLink": null,
			"recordId": "ka08b000000QxhCAAS",
			"order": 3,
			"name": "set-up-",
			"label": "Create a  Account",
			"items": [],
			"isKnowledge": true,
			"identityKeyName": null,
			"identityKeyDesc": null,
			"expanded": false,
			"description": "Learn how to create a  account to log into Ads Manager.",
			"articleType": "Forbusiness External"
		},
		{
			"topicLink": null,
			"recordId": "ka08b000000btJTAAY",
			"order": 4,
			"name": "business-countries",
			"label": "Countries Available for Business Signup",
			"items": [],
			"isKnowledge": true,
			"identityKeyName": null,
			"identityKeyDesc": null,
			"expanded": false,
			"description": "View the list of countries available for Business Signup.",
			"articleType": "Forbusiness External"
		},
		{
			"topicLink": null,
			"recordId": "ka00y000000kD2yAAE",
			"order": 5,
			"name": "reset-password",
			"label": "Reset Your  Password",
			"items": [],
			"isKnowledge": true,
			"identityKeyName": null,
			"identityKeyDesc": null,
			"expanded": false,
			"description": "Learn how to reset your password from the  Log In screen.",
			"articleType": "Forbusiness External"
		},
		{
			"topicLink": null,
			"recordId": "ka08b000000bslHAAQ",
			"order": 6,
			"name": "get-started",
			"label": "Set Up a Business Account",
			"items": [],
			"isKnowledge": true,
			"identityKeyName": null,
			"identityKeyDesc": null,
			"expanded": false,
			"description": "Learn how to set up a Business Account to begin advertising with  Inc.",
			"articleType": "Forbusiness External"
		},
		{
			"topicLink": null,
			"recordId": "ka00y000000bs2lAAA",
			"order": 7,
			"name": "username-email",
			"label": "Log In with Your Username or Email",
			"items": [],
			"isKnowledge": true,
			"identityKeyName": null,
			"identityKeyDesc": null,
			"expanded": false,
			"description": "Learn how to log into Ads Manager with different credentials.",
			"articleType": "Forbusiness External"
		},
		{
			"topicLink": null,
			"recordId": "ka00y000000g1ZNAAY",
			"order": 8,
			"name": "global-navigation",
			"label": "Ads Manager",
			"items": [],
			"isKnowledge": true,
			"identityKeyName": null,
			"identityKeyDesc": null,
			"expanded": false,
			"description": "Learn how to create and manage your  ads in Ads Manager.",
			"articleType": "Forbusiness External"
		},
		{
			"topicLink": null,
			"recordId": "ka08b000000QxaQAAS",
			"order": 8,
			"name": "create-ad-account",
			"label": "Create an Ad Account",
			"items": [],
			"isKnowledge": true,
			"identityKeyName": null,
			"identityKeyDesc": null,
			"expanded": false,
			"description": "Learn about ad accounts and how to create them.",
			"articleType": "Forbusiness External"
		},
		{
			"topicLink": null,
			"recordId": "ka08b000000bt17AAA",
			"order": 9,
			"name": "-focus",
			"label": " Focus",
			"items": [],
			"isKnowledge": true,
			"identityKeyName": null,
			"identityKeyDesc": null,
			"expanded": false,
			"description": " Focus is an online learning portal where you can develop your expertise in  advertising solutions. ",
			"articleType": "Forbusiness External"
		},
		{
			"topicLink": null,
			"recordId": "ka08b000000N7KKAA0",
			"order": 10,
			"name": "creator-marketplace",
			"label": "’s Creator Marketplace",
			"items": [],
			"isKnowledge": true,
			"identityKeyName": null,
			"identityKeyDesc": null,
			"expanded": false,
			"description": "Learn about ’s Creator Marketplace which enables businesses to discover and partner with ’s creator community.",
			"articleType": "Forbusiness External"
		},
		{
			"topicLink": null,
			"recordId": "ka08b000000bt15AAA",
			"order": 12,
			"name": "-trends",
			"label": " Trends",
			"items": [],
			"isKnowledge": true,
			"identityKeyName": null,
			"identityKeyDesc": null,
			"expanded": false,
			"description": "Learn more about the topics, people, and moments that are important to ters with  Trends.",
			"articleType": "Forbusiness External"
		},
		{
			"topicLink": "/s/topic/0TO0y000000cZSDGA2/Ad Review",
			"recordId": "0TO0y000000cZSDGA2",
			"order": null,
			"name": "Ad Review",
			"label": "Ad Review",
			"items": [{
				"topicLink": null,
				"recordId": "ka00y000000brsvAAA",
				"order": 1,
				"name": "ad-review",
				"label": "About the Ad Review Process",
				"items": [],
				"isKnowledge": true,
				"identityKeyName": null,
				"identityKeyDesc": null,
				"expanded": false,
				"description": "When you submit ads on  they'll be subject to an ad review process.",
				"articleType": "Forbusiness External"
			},
			{
				"topicLink": null,
				"recordId": "ka00y000000bs5HAAQ",
				"order": 2,
				"name": "ad-rejection-reason",
				"label": "View Why Your Ad was Rejected",
				"items": [],
				"isKnowledge": true,
				"identityKeyName": null,
				"identityKeyDesc": null,
				"expanded": false,
				"description": "If your ad was not approved, you can review the rejection reason in Ads Manager.",
				"articleType": "Forbusiness External"
			}
			],
			"isKnowledge": false,
			"identityKeyName": "BHC-0005",
			"identityKeyDesc": null,
			"expanded": false,
			"description": null,
			"articleType": null
		},
		{
			"topicLink": "/s/topic/0TO0y000000YklvGAC/Public Profiles for Businesses",
			"recordId": "0TO0y000000YklvGAC",
			"order": null,
			"name": "Public Profiles for Businesses",
			"label": "Public Profiles for Businesses",
			"items": [{
				"topicLink": null,
				"recordId": "ka08b000000N7K3AAK",
				"order": 1,
				"name": "public-profiles",
				"label": "What is a Public Profile for Business?",
				"items": [],
				"isKnowledge": true,
				"identityKeyName": null,
				"identityKeyDesc": null,
				"expanded": false,
				"description": "Learn about Public Profiles for Businesses.",
				"articleType": "Forbusiness External"
			},
			{
				"topicLink": null,
				"recordId": "ka08b000000QxomAAC",
				"order": 2,
				"name": "public-profiles-business",
				"label": "How to Set up a Public Profile for Your Business",
				"items": [],
				"isKnowledge": true,
				"identityKeyName": null,
				"identityKeyDesc": null,
				"expanded": false,
				"description": "Learn how to set up a Public Profile for your Business.",
				"articleType": "Forbusiness External"
			},
			{
				"topicLink": "/s/topic/0TO8b000000csEmGAI/Public Profiles Members, Roles, & Permissions",
				"recordId": "0TO8b000000csEmGAI",
				"order": null,
				"name": "Public Profiles Members, Roles, & Permissions",
				"label": "Public Profiles Members, Roles, & Permissions",
				"items": [{
					"topicLink": null,
					"recordId": "ka08b000000btXBAAY",
					"order": 1,
					"name": "Public-Profile-Members",
					"label": "Add and Manage Public Profile Members",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Learn how to add and manage members of your Public Profile.",
					"articleType": "Forbusiness External"
				},
				{
					"topicLink": null,
					"recordId": "ka08b000000QxakAAC",
					"order": 2,
					"name": "public-profile-roles",
					"label": "Public Profiles Member Roles and Permissions",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Learn about the different roles and permissions you can assign for Public Profiles for Businesses.",
					"articleType": "Forbusiness External"
				}
				],
				"isKnowledge": false,
				"identityKeyName": null,
				"identityKeyDesc": null,
				"expanded": false,
				"description": null,
				"articleType": null
			},
			{
				"topicLink": "/s/topic/0TO8b000000csC8GAI/Manage Your Public Profile",
				"recordId": "0TO8b000000csC8GAI",
				"order": null,
				"name": "Manage Your Public Profile",
				"label": "Manage Your Public Profile",
				"items": [{
					"topicLink": null,
					"recordId": "ka08b000000N7JyAAK",
					"order": 1,
					"name": "public-profile-verify",
					"label": "Verify Your Public Profile",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Learn how to verify a Public Profile.",
					"articleType": "Forbusiness External"
				},
				{
					"topicLink": null,
					"recordId": "ka08b000000btXCAAY",
					"order": 2,
					"name": "manage-public-profile",
					"label": "Profile Subscribers",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "ters have the option to subscribe to your account.",
					"articleType": "Forbusiness External"
				},
				{
					"topicLink": null,
					"recordId": "ka08b000000VU6fAAG",
					"order": 3,
					"name": "Chat-and-Story-Replies",
					"label": "Story and Spotlight Replies",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Learn about how to use Story and Spotlight Replies with your Public Profile.",
					"articleType": "Forbusiness External"
				},
				{
					"topicLink": null,
					"recordId": "ka08b000000N6xNAAS",
					"order": 4,
					"name": "profile-metrics",
					"label": "Public Profiles Metrics and Analytics",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Learn about the different Public Profile metrics and analytics you can access.",
					"articleType": "Forbusiness External"
				},
				{
					"topicLink": null,
					"recordId": "ka08b000000btXAAAY",
					"order": 5,
					"name": "revert-public-profile",
					"label": "Delete Your Public Profile",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Learn how to revert your public profile back to a standard  profile.",
					"articleType": "Forbusiness External"
				}
				],
				"isKnowledge": false,
				"identityKeyName": null,
				"identityKeyDesc": null,
				"expanded": false,
				"description": null,
				"articleType": null
			},
			{
				"topicLink": "/s/topic/0TO8b000000csC9GAI/Public Profile Creative Best Practices",
				"recordId": "0TO8b000000csC9GAI",
				"order": null,
				"name": "Public Profile Creative Best Practices",
				"label": "Public Profile Creative Best Practices",
				"items": [{
					"topicLink": null,
					"recordId": "ka08b000000btWkAAI",
					"order": 1,
					"name": "public-profile-creative",
					"label": "Public Profile Creative Recommendations",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Learn about creative best practices to get the most out of your Public Profile.",
					"articleType": "Forbusiness External"
				},
				{
					"topicLink": null,
					"recordId": "ka08b000000btXGAAY",
					"order": 2,
					"name": "creator-content",
					"label": "Collaborate with a Creator on Content",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Create engaging content by collaborating with our Creators.",
					"articleType": "Forbusiness External"
				}
				],
				"isKnowledge": false,
				"identityKeyName": null,
				"identityKeyDesc": null,
				"expanded": false,
				"description": null,
				"articleType": null
			},
			{
				"topicLink": "/s/topic/0TO8b000000csCAGAY/Posting Content With Public Profiles",
				"recordId": "0TO8b000000csCAGAY",
				"order": null,
				"name": "Posting Content With Public Profiles",
				"label": "Posting Content With Public Profiles",
				"items": [{
					"topicLink": null,
					"recordId": "ka08b000000VUKhAAO",
					"order": 1,
					"name": "public-profiles-content",
					"label": "Post to Your Public Story",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Learn how to post content to your Public Story.",
					"articleType": "Forbusiness External"
				},
				{
					"topicLink": null,
					"recordId": "ka08b000000N7KDAA0",
					"order": 2,
					"name": "saved-stories",
					"label": "Add Saved Stories to Your Public Profile",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Learn how to add Saved Stories to your Public Profile.",
					"articleType": "Forbusiness External"
				},
				{
					"topicLink": null,
					"recordId": "ka08b000000Qxh8AAC",
					"order": 3,
					"name": "spotlight-profile-content",
					"label": "Post Spotlights to your Profile",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Share your Spotlight content on your Public Profile.",
					"articleType": "Forbusiness External"
				},
				{
					"topicLink": null,
					"recordId": "ka08b000000QxafAAC",
					"order": 4,
					"name": "public-profile-lenses",
					"label": "Add AR Lenses to Your Public Profile",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Learn how to add AR Lenses to your Public Profile.",
					"articleType": "Forbusiness External"
				}
				],
				"isKnowledge": false,
				"identityKeyName": null,
				"identityKeyDesc": null,
				"expanded": false,
				"description": null,
				"articleType": null
			},
			{
				"topicLink": "/s/topic/0TO8b000000csEnGAI/Advertise With Your Public Profile",
				"recordId": "0TO8b000000csEnGAI",
				"order": null,
				"name": "Advertise With Your Public Profile",
				"label": "Advertise With Your Public Profile",
				"items": [{
					"topicLink": null,
					"recordId": "ka08b000000N7J0AAK",
					"order": 1,
					"name": "profile-ad-account",
					"label": "Link an Ad Account to Your Public Profile",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Learn how to link an ad account to your Public Profile. Also learn how to unlink an ad account from your Profile.",
					"articleType": "Forbusiness External"
				},
				{
					"topicLink": null,
					"recordId": "ka08b000000N6wiAAC",
					"order": 2,
					"name": "drive-profile-ads",
					"label": "Drive to Your Profile from Ads",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Learn how to drive to your Public Profile from your ads.",
					"articleType": "Forbusiness External"
				},
				{
					"topicLink": null,
					"recordId": "ka08b000000N7JwAAK",
					"order": 3,
					"name": "deeplink-ad-profile",
					"label": "Deeplink from an Ad to your Public Profile",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Learn how to deeplink from an ad to your Profile.",
					"articleType": "Forbusiness External"
				}
				],
				"isKnowledge": false,
				"identityKeyName": null,
				"identityKeyDesc": null,
				"expanded": false,
				"description": null,
				"articleType": null
			},
			{
				"topicLink": "/s/topic/0TO8b000000csEoGAI/Use Organic Content In Ads",
				"recordId": "0TO8b000000csEoGAI",
				"order": null,
				"name": "Use Organic Content In Ads",
				"label": "Use Organic Content In Ads",
				"items": [{
					"topicLink": null,
					"recordId": "ka08b000000VUHJAA4",
					"order": 1,
					"name": "organic-content-ads",
					"label": "Promote Organic Content with Ads",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Promote your Organic Story or Saved Story content with ads.",
					"articleType": "Forbusiness External"
				}],
				"isKnowledge": false,
				"identityKeyName": null,
				"identityKeyDesc": null,
				"expanded": false,
				"description": null,
				"articleType": null
			},
			{
				"topicLink": "/s/topic/0TO8b0000006WrAGAU/Set Up a Store For Your Public Profile",
				"recordId": "0TO8b0000006WrAGAU",
				"order": null,
				"name": "Set Up a Store For Your Public Profile",
				"label": "Set Up a Store For Your Public Profile",
				"items": [{
					"topicLink": null,
					"recordId": "ka08b000000N7JeAAK",
					"order": 1,
					"name": "public-profile-shop",
					"label": "How to Create Your Store",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Learn how to set up a Store within your Public Profile.",
					"articleType": "Forbusiness External"
				},
				{
					"topicLink": null,
					"recordId": "ka08b000000N7JjAAK",
					"order": 2,
					"name": "organizing-stores",
					"label": "How to Organize Your Store",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Learn how to create categories to make it easier for ters to navigate.",
					"articleType": "Forbusiness External"
				},
				{
					"topicLink": null,
					"recordId": "ka08b000000N7JoAAK",
					"order": 3,
					"name": "stores-product-tagging",
					"label": "Driving Traffic with Product Tagging",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Learn how to drive additional organic distribution with product tagging from your Store.",
					"articleType": "Forbusiness External"
				},
				{
					"topicLink": null,
					"recordId": "ka08b000000N7JtAAK",
					"order": 4,
					"name": "store-products-shopping-lenses",
					"label": "Adding Store Products to Catalog-Powered Shopping Lenses",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Learn how to add products from your Store to AR try-on lenses, powered by the catalog.",
					"articleType": "Forbusiness External"
				},
				{
					"topicLink": null,
					"recordId": "ka08b000000N7JuAAK",
					"order": 5,
					"name": "store-engagement",
					"label": "Analyzing Your Store’s Engagement",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Evaluate how ters are engaging with your Store within the Analytics reporting tab.",
					"articleType": "Forbusiness External"
				},
				{
					"topicLink": null,
					"recordId": "ka08b000000Qxb0AAC",
					"order": 6,
					"name": "store-best-practices",
					"label": "Best Practices for Public Profile Stores",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Learn about setup best practices to get the most out of your Store.",
					"articleType": "Forbusiness External"
				}
				],
				"isKnowledge": false,
				"identityKeyName": null,
				"identityKeyDesc": null,
				"expanded": false,
				"description": null,
				"articleType": null
			}
			],
			"isKnowledge": false,
			"identityKeyName": "BHC-0035",
			"identityKeyDesc": null,
			"expanded": false,
			"description": null,
			"articleType": null
		}
		],
		"isKnowledge": false,
		"identityKeyName": "BHC-0022",
		"identityKeyDesc": null,
		"expanded": false,
		"description": null,
		"articleType": null
	},
	{
		"topicLink": "/s/topic/0TO0y000000YVcDGAW/Account Management",
		"Id": "0TO0y000000YVcDGAW",
		"order": null,
		"name": "Account Management",
		"label": "Account Management",
		"items": [{
			"topicLink": null,
			"recordId": "ka00y000000brt5AAA",
			"order": 1,
			"name": "biz-acct-id",
			"label": "Find Your Organization and Ad Account ID",
			"items": [],
			"isKnowledge": true,
			"identityKeyName": null,
			"identityKeyDesc": null,
			"expanded": false,
			"description": "Find your Organization and Ad Account ID in Ads Manager.",
			"articleType": "Forbusiness External"
		},
		{
			"topicLink": null,
			"recordId": "ka08b000000VUH4AAO",
			"order": 6,
			"name": "language-settings",
			"label": "Language Settings",
			"items": [],
			"isKnowledge": true,
			"identityKeyName": null,
			"identityKeyDesc": null,
			"expanded": false,
			"description": "Change Ads Manager to your preferred language.",
			"articleType": "Forbusiness External"
		},
		{
			"topicLink": null,
			"recordId": "ka08b000000btH3AAI",
			"order": 7,
			"name": "email-notifications",
			"label": "Notifications",
			"items": [],
			"isKnowledge": true,
			"identityKeyName": null,
			"identityKeyDesc": null,
			"expanded": false,
			"description": "Receive notifications regarding your ads.",
			"articleType": "Forbusiness External"
		},
		{
			"topicLink": "/s/topic/0TO0y000000YVcVGAW/Manage Members and Roles",
			"recordId": "0TO0y000000YVcVGAW",
			"order": null,
			"name": "Manage Members and Roles",
			"label": "Manage Members and Roles",
			"items": [{
				"topicLink": null,
				"recordId": "ka08b000000N7KOAA0",
				"order": 1,
				"name": "manage-members",
				"label": "Manage Members",
				"items": [],
				"isKnowledge": true,
				"identityKeyName": null,
				"identityKeyDesc": null,
				"expanded": false,
				"description": "Learn how to invite members to your business and ad accounts, edit their roles and permissions, and remove members.",
				"articleType": "Forbusiness External"
			},
			{
				"topicLink": null,
				"recordId": "ka08b000000N6xbAAC",
				"order": 2,
				"name": "roles-permissions",
				"label": "Roles and Permissions",
				"items": [],
				"isKnowledge": true,
				"identityKeyName": null,
				"identityKeyDesc": null,
				"expanded": false,
				"description": "Depending on your role, you may have different levels of functionality and access to a business or ad account. ",
				"articleType": "Forbusiness External"
			}
			],
			"isKnowledge": false,
			"identityKeyName": "BHC-0028",
			"identityKeyDesc": null,
			"expanded": false,
			"description": null,
			"articleType": null
		},
		{
			"topicLink": "/s/topic/0TO0y000000cZIIGA2/Billing & Payments",
			"recordId": "0TO0y000000cZIIGA2",
			"order": null,
			"name": "Billing & Payments",
			"label": "Billing & Payments",
			"items": [{
				"topicLink": "/s/topic/0TO8b0000006Wu9GAE/How Billing Works",
				"recordId": "0TO8b0000006Wu9GAE",
				"order": null,
				"name": "How Billing Works",
				"label": "How Billing Works",
				"items": [{
					"topicLink": null,
					"recordId": "ka08b000000QwsfAAC",
					"order": 1,
					"name": "payment-methods",
					"label": "Billing & Payments in Ads Manager",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Access Billing & Payments in Ads Manager to set up and manage your payment methods.",
					"articleType": "Forbusiness External"
				},
				{
					"topicLink": null,
					"recordId": "ka08b000000QxneAAC",
					"order": 2,
					"name": "billing-thresholds",
					"label": "About Billing Thresholds",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Learn more about how billing thresholds affect the frequency of charges and spend.",
					"articleType": "Forbusiness External"
				}
				],
				"isKnowledge": false,
				"identityKeyName": null,
				"identityKeyDesc": null,
				"expanded": false,
				"description": "Learn how to access and manage your billing and payment details within Ads Manager",
				"articleType": null
			},
			{
				"topicLink": "/s/topic/0TO8b0000006WuAGAU/Payment Methods",
				"recordId": "0TO8b0000006WuAGAU",
				"order": null,
				"name": "Payment Methods",
				"label": "Payment Methods",
				"items": [{
					"topicLink": null,
					"recordId": "ka08b000000VTtKAAW",
					"order": 1,
					"name": "establish-credit",
					"label": "How to Establish a Line of Credit",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Set up and manage a line of credit payment method.",
					"articleType": "Forbusiness External"
				},
				{
					"topicLink": null,
					"recordId": "ka08b000000VTsqAAG",
					"order": 2,
					"name": "add-credit-card",
					"label": "How to Add or Remove a Credit Card",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Set up and manage a credit card payment method.",
					"articleType": "Forbusiness External"
				},
				{
					"topicLink": null,
					"recordId": "ka08b000000VTt5AAG",
					"order": 3,
					"name": "add-paypal",
					"label": "How to Add or Remove a Paypal Account",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Set up and manage a Paypal payment method.",
					"articleType": "Forbusiness External"
				},
				{
					"topicLink": null,
					"recordId": "ka08b000000VUOgAAO",
					"order": 4,
					"name": "payment-availability-by-country",
					"label": "Payment Options Available By Country",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Learn which countries are eligible to establish a line of credit, pay with a credit card, or pay with a Paypal account.",
					"articleType": "Forbusiness External"
				},
				{
					"topicLink": null,
					"recordId": "ka08b000000QwtsAAC",
					"order": 5,
					"name": "switch-payment-methods",
					"label": "How to Switch Payment Methods",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Learn how to manage and change your payment methods.",
					"articleType": "Forbusiness External"
				},
				{
					"topicLink": null,
					"recordId": "ka08b000000QwtxAAC",
					"order": 7,
					"name": "apply-offers-coupons",
					"label": "How to Apply Offers and Coupons",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Pay with a coupon or offer code.",
					"articleType": "Forbusiness External"
				},
				{
					"topicLink": null,
					"recordId": "ka08b000000Qwu2AAC",
					"order": 8,
					"name": "tax-requirements-formats",
					"label": "Tax ID Requirements and Formats",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Learn more about your specific country's tax ID requirements.",
					"articleType": "Forbusiness External"
				},
				{
					"topicLink": null,
					"recordId": "ka08b000000Qwu7AAC",
					"order": 9,
					"name": "retry-payments",
					"label": "Declined Payments",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "If your ads are paused due to a failed charge, you can retry the payment method.",
					"articleType": "Forbusiness External"
				},
				{
					"topicLink": null,
					"recordId": "ka08b000000QxMXAA0",
					"order": 9,
					"name": "credit-card-verification",
					"label": "Verify Your Credit Card",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Learn how to verify your credit card payment method.",
					"articleType": "Forbusiness External"
				},
				{
					"topicLink": null,
					"recordId": "ka08b000000VUEoAAO",
					"order": 10,
					"name": "prepay",
					"label": "How Prepay Works (Manual Payments)",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Learn how to set up Prepay in your Ads Manager account.",
					"articleType": "Forbusiness External"
				}
				],
				"isKnowledge": false,
				"identityKeyName": null,
				"identityKeyDesc": null,
				"expanded": false,
				"description": "Learn how to set up and manage your payment methods, apply coupons, and learn about tax ID requirements and formats.",
				"articleType": null
			},
			{
				"topicLink": "/s/topic/0TO8b0000006WuCGAU/Receipts And Invoices",
				"recordId": "0TO8b0000006WuCGAU",
				"order": null,
				"name": "Receipts And Invoices",
				"label": "Receipts And Invoices",
				"items": [{
					"topicLink": null,
					"recordId": "ka08b000000QxhWAAS",
					"order": 1,
					"name": "billing-management",
					"label": "Access Ad Invoices and Receipts",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Find out how to access and manage your receipts and invoices.",
					"articleType": "Forbusiness External"
				},
				{
					"topicLink": null,
					"recordId": "ka08b000000VTtPAAW",
					"order": 2,
					"name": "pay-invoice",
					"label": "Pay an Invoice",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Set up direct debit and manage invoices.",
					"articleType": "Forbusiness External"
				},
				{
					"topicLink": null,
					"recordId": "ka08b000000QxMSAA0",
					"order": 3,
					"name": "filter-receipts",
					"label": "Access On-Demand Filter Receipts",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Learn how to view your transaction details.",
					"articleType": "Forbusiness External"
				},
				{
					"topicLink": null,
					"recordId": "ka08b000000QxMTAA0",
					"order": 4,
					"name": "billing-address",
					"label": "Add a Billing Center",
					"items": [],
					"isKnowledge": true,
					"identityKeyName": null,
					"identityKeyDesc": null,
					"expanded": false,
					"description": "Manage your Business billing addresses and contact information.",
					"articleType": "Forbusiness External"
				}
				],
				"isKnowledge": false,
				"identityKeyName": null,
				"identityKeyDesc": null,
				"expanded": false,
				"description": "Learn how to access and manage your receipts and invoices.",
				"articleType": null
			}
			],
			"isKnowledge": false,
			"identityKeyName": null,
			"identityKeyDesc": null,
			"expanded": false,
			"description": null,
			"articleType": null
		},
		{
			"topicLink": "/s/topic/0TO0y000000cYW0GAM/'s API",
			"recordId": "0TO0y000000cYW0GAM",
			"order": null,
			"name": "'s API",
			"label": "'s API",
			"items": [{
				"topicLink": null,
				"recordId": "ka08b000000N6x3AAC",
				"order": 1,
				"name": "api-apply",
				"label": "Activate Access to the  Marketing API",
				"items": [],
				"isKnowledge": true,
				"identityKeyName": null,
				"identityKeyDesc": null,
				"expanded": false,
				"description": "Learn how to activate access to 's Marketing API.",
				"articleType": "Forbusiness External"
			},
			{
				"topicLink": null,
				"recordId": "ka08b000000VUMYAA4",
				"order": 2,
				"name": "api-faq",
				"label": " Marketing API FAQs",
				"items": [],
				"isKnowledge": true,
				"identityKeyName": null,
				"identityKeyDesc": null,
				"expanded": false,
				"description": "Find answers to frequently asked questions about 's Marketing API.",
				"articleType": "Forbusiness External"
			}
			],
			"isKnowledge": false,
			"identityKeyName": "BHC-0042",
			"identityKeyDesc": null,
			"expanded": false,
			"description": null,
			"articleType": null
		},
		{
			"topicLink": "/s/topic/0TO0y000000cZJaGAM/ App ID",
			"recordId": "0TO0y000000cZJaGAM",
			"order": null,
			"name": " App ID",
			"label": " App ID",
			"items": [{
				"topicLink": null,
				"recordId": "ka08b000000VUPtAAO",
				"order": 1,
				"name": "-app-id",
				"label": "Set Up and Manage Your  App ID",
				"items": [],
				"isKnowledge": true,
				"identityKeyName": null,
				"identityKeyDesc": null,
				"expanded": false,
				"description": "The  App ID is a unique code generated by an advertiser in the  Ads Manager.",
				"articleType": "Forbusiness External"
			},
			{
				"topicLink": null,
				"recordId": "ka00y000000bsSAAAY",
				"order": 2,
				"name": "app-id-tracking",
				"label": " App ID Tracking Toggle",
				"items": [],
				"isKnowledge": true,
				"identityKeyName": null,
				"identityKeyDesc": null,
				"expanded": false,
				"description": "The  App ID Tracking Toggle is an Ads Manager button, making it easy to track and report on app conversions resulting.",
				"articleType": "Forbusiness External"
			}
			],
			"isKnowledge": false,
			"identityKeyName": "BHC-0039",
			"identityKeyDesc": null,
			"expanded": false,
			"description": null,
			"articleType": null
		}
		],
		"isKnowledge": false,
		"identityKeyName": "BHC-0001",
		"identityKeyDesc": null,
		"expanded": false,
		"description": null,
		"articleType": null
	}
	]

   @track dragStart;
  @track ElementList = [];

  connectedCallback() {
    getAccountList()
      .then((result) => {
        for (let i = 0; i < result.length; i++) {
          this.ElementList.push(result[i]);
		}
		 
      })
      .catch((error) => {
        console.log("###Error : " + error.body.message);
	  });
	  
  }
  DragStart(event) {
    this.dragStart = event.target.title;
    event.target.classList.add("drag");
  }

  DragOver(event) {
    event.preventDefault();
    return false;
  }

  Drop(event) {
    event.stopPropagation();
    const DragValName = this.dragStart;
    const DropValName = event.target.title;
    if (DragValName === DropValName) {
      return false;
    }
    const index = DropValName;
    const currentIndex = DragValName;
    const newIndex = DropValName;
    Array.prototype.move = function (from, to) {
      this.splice(to, 0, this.splice(from, 1)[0]);
    };
    this.ElementList.move(currentIndex, newIndex);
  }
}